# Set up and run this Streamlit App
import streamlit as st
import pandas as pd
# from helper_functions import llm # <--- Not needed anymore. The helper function is now directly called by `customer_query_handler` 🆕
from logics.customer_query_handler import process_user_message

# region <--------- Streamlit App Configuration --------->
st.set_page_config(
    layout="centered",
    page_title="My Streamlit App"
)
# endregion <--------- Streamlit App Configuration --------->

st.title("Streamlit App")

form = st.form(key="form")
form.subheader("Prompt")

user_prompt = form.text_area("Enter your prompt here", height=200)

if form.form_submit_button("Submit"):
    st.toast(f"User Input Submitted - {user_prompt}")
    print(f"User Input is {user_prompt}")
    st.divider()
    # response = llm.get_completion(user_prompt) # <--- This calls the helper function that we have created 🆕
    response, course_details = process_user_message(user_prompt) #<--- This calls the `process_user_message` function that we have created 
    st.write(response) # <--- This displays the response generated by the LLM onto the frontend 🆕
    st.divider()
    print(course_details)
    df = pd.DataFrame(course_details)
    df

